name: Custom Cl Workflow

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Download ngrok
      run: wget -q -O ngrok.zip https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip

    - name: Extract ngrok
      run: unzip -o ngrok.zip && chmod +x ngrok

    - name: Authenticate with ngrok
      run: ./ngrok authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Install xrdp and xfce4
      run: sudo apt-get update && sudo apt-get install -y xrdp xfce4

    - name: Configure xrdp to use xfce4
      run: echo xfce4-session >~/.xsession

    - name: Start xrdp service
      run: sudo service xrdp start

    - name: Create ngrok Tunnel
      run: ./ngrok tcp
